ignore:
  - 'Mini Model <minimodel@metamodel.me>'

exclude:
  - /^src\/Resources\/contao\/languages/

mapping:
  'Stefan Heimes <stefan_heimes@hotmail.com>': 'Stefan heimes <stefan_heimes@hotmail.com>'
